version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: flexisafquiz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2326
    ports:
      - "4000:5432"

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=flexisafquiz
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=2326
    depends_on:
      - postgres
